language: go

go:
  - tip

install: 
  - go get -t -v ./...

after_success:
  - bash build/travis-after_success.sh

before_deploy: 
  - gem install fpm
  - gem install package_cloud
  - ruby build/travis-before_deploy.rb

deploy:
  provider: script
  script: "bash $TRAVIS_BUILD_DIR/build/travis-deploy.sh"
  skip_cleanup: true
  on: 
    branch: travis-ci-migration